### ISSUE TITLE
Question about input of synthesize_early/medium/large_tumor

### ISSUE THREAD

**Issue by ChangranXU** [MrGiovanni/DiffTumor#3]
Hi!

Thanks for your contribution! 

I want to generate tumor, and I found that there's no direct code or tutorial to do that, so I tried to write code to complete that utilizing the function in DiffTumor/STEP3.SegmentationModel/TumorGeneration/utils.py. I have downloaded the pertained model and successfully load the synt_model_prepare function.

However, I have a question about the type of input in the function synthesize_early/medium/large_tumor. May I ask what should the input type of the ct_volume and organ_mask be?

```
import nibabel as nb

vqgan,early_sampler,noearly_sampler= synt_model_prepare(device = torch.device("cuda",0),fold=0,organ=model_type)

ct_volumn = nb.load(os.path.join(path_to_the_original_ct)).get_fdata()
ct_volumn =torch.from_numpy(ct_volumn).to(torch.device("cuda",0))
ct_volumn = ct_volumn[None,...]

#organ segmentation ct
organ_mask = nb.load(os.path.join(path_to_the_segmented_ct_from_the_original_ct)).get_fdata()
organ_mask =torch.from_numpy(organ_mask).to(torch.device("cuda",0))
organ_mask = organ_mask[None,...]

synt_data, synt_target = synthesize_early_tumor(healthy_data, seg_file, model_type, vqgan, early_sampler)
```
It raised error like:
```
Traceback (most recent call last):
  File "/DiffTumor/STEP3.SegmentationModel/generate_tumor.py", line 57, in <module>
    synt_data, synt_target = synthesize_early_tumor(healthy_data, seg_file, model_type, vqgan, early_sampler)
  File "/DiffTumor/STEP3.SegmentationModel/TumorGeneration/utils.py", line 273, in synthesize_early_tumor
    tumor_mask = get_fixed_geo(organ_mask_np[bs,0], synthetic_tumor_type, organ_type)
  File "/DiffTumor/STEP3.SegmentationModel/TumorGeneration/utils.py", line 91, in get_fixed_geo
    geo_mask = np.zeros((mask_scan.shape[0] + enlarge_x, mask_scan.shape[1] + enlarge_y, mask_scan.shape[2] + enlarge_z), dtype=np.int8)
IndexError: tuple index out of range
```
So I tried to modified the organ_mask's dimension:
```
organ_mask = organ_mask[None,...]
organ_mask = organ_mask[None,...]
```
And the code stuck at the 
```
  File "/DiffTumor/STEP3.SegmentationModel/TumorGeneration/utils.py", line 273, in synthesize_early_tumor
    tumor_mask = get_fixed_geo(organ_mask_np[bs,0], synthetic_tumor_type, organ_type)
  File "/DiffTumor/STEP3.SegmentationModel/TumorGeneration/utils.py", line 129, in get_fixed_geo
    point = random_select(mask_scan, organ_type)
  File "/DiffTumor/STEP3.SegmentationModel/TumorGeneration/utils.py", line 34, in random_select
    liver_mask = cv2.erode(liver_mask, kernel, iterations=1)
KeyboardInterrupt
```
Thanks a lot if you could help me.

**Comment by qic999** [comment]
@ChangranXU Thank you for your attention to our work!  The tensor size for `healthy_data` and `healthy_target` should be [bs, channel, args.roi_x, args.roi_y, args.roi_z], as in [1, 1, 96, 96, 96].  Therefore, in your code, you should proceed as follows:

```
ct_volumn = nb.load(os.path.join(path_to_the_original_ct)).get_fdata()
ct_volumn =torch.from_numpy(ct_volumn).to(torch.device("cuda",0))
ct_volumn = ct_volumn[None,None,...]

#organ segmentation ct
organ_mask = nb.load(os.path.join(path_to_the_segmented_ct_from_the_original_ct)).get_fdata()
organ_mask =torch.from_numpy(organ_mask).to(torch.device("cuda",0))
organ_mask = organ_mask[None,None,...]
```
